import { HfInference } from "@huggingface/inference";

export class LLMService {
  /**
   * Generates an answer using a HuggingFace LLM given a fully constructed prompt.
   * 
   * @param prompt The complete RAG prompt
   * @param model The specific HuggingFace model string (e.g. "Qwen/Qwen3-8B")
   * @returns The generated plain-text answer
   */
  static async generateAnswer(prompt: string, model: string): Promise<string> {
    const apiKey = process.env.HUGGINGFACE_API_KEY;

    if (!apiKey) {
      throw new Error("Missing HUGGINGFACE_API_KEY environment variable.");
    }

    const hf = new HfInference(apiKey);

    try {
      const response = await hf.chatCompletion({
        model: model,
        messages: [{ role: "user", content: prompt }],
        max_tokens: 512,
        temperature: 0.1,
      });

      const generatedContent = response.choices?.[0]?.message?.content;

      if (!generatedContent) {
        throw new Error("No response generated by LLM.");
      }

      return generatedContent.trim();
    } catch (error: any) {
      console.error(`[LLMService] Error generating answer with model ${model}:`, error);
      throw new Error(`LLM Generation Failed: ${error.message}`);
    }
  }

  /**
   * Generates a streaming answer using a HuggingFace LLM given a fully constructed prompt.
   * 
   * @param prompt The complete RAG prompt
   * @param model The specific HuggingFace model string (e.g. "Qwen/Qwen3-8B")
   * @returns A ReadableStream of text chunks
   */
  static generateAnswerStream(prompt: string, model: string): ReadableStream {
    const apiKey = process.env.HUGGINGFACE_API_KEY;

    if (!apiKey) {
      throw new Error("Missing HUGGINGFACE_API_KEY environment variable.");
    }

    const hf = new HfInference(apiKey);

    return new ReadableStream({
      async start(controller) {
        try {
          const stream = hf.chatCompletionStream({
            model: model,
            messages: [{ role: "user", content: prompt }],
            max_tokens: 2048,
            temperature: 0.1,
          });

          let isFirstChunk = true;
          const encoder = new TextEncoder();

          for await (const chunk of stream) {
            let content = chunk.choices?.[0]?.delta?.content ?? "";

            if (isFirstChunk) {
              content = content.replace(/^\s+/, "");
              if (content) {
                isFirstChunk = false;
              }
            }

            if (content) {
              controller.enqueue(encoder.encode(content));
            }
          }
          controller.close();
        } catch (error: any) {
          console.error(`[LLMService] Error streaming answer with model ${model}:`, error);
          controller.error(error);
        }
      }
    });
  }

  /**
   * Generates a concise title for a chat based on the first user message.
   * 
   * @param firstUserMessage The first message sent by the user
   * @param model The specific HuggingFace model string (e.g. "Qwen/Qwen3-8B")
   * @returns A string up to 6 words long
   */
  static async generateChatTitle(firstUserMessage: string, model: string): Promise<string> {
    const apiKey = process.env.HUGGINGFACE_API_KEY;

    if (!apiKey) {
      throw new Error("Missing HUGGINGFACE_API_KEY environment variable.");
    }

    const hf = new HfInference(apiKey);

    const prompt = `You generate concise conversation titles.
Maximum 6 words.
No quotes.
No punctuation at the end.
Return only the title.

User: ${firstUserMessage}
Title:`;

    try {
      const response = await hf.chatCompletion({
        model: model,
        messages: [{ role: "user", content: prompt }],
        max_tokens: 15,
        temperature: 0.3,
      });

      let title = response.choices?.[0]?.message?.content?.trim();

      if (!title) {
        // Fallback to user message
        let fallback = firstUserMessage.trim();
        if (fallback.length > 60) {
          fallback = fallback.substring(0, 57) + "...";
        }
        return fallback;
      }

      // Clean up any quotes or punctuation just in case the LLM ignored instructions
      title = title.replace(/^["']|["']$/g, '').replace(/[.!?]$/, '');
      
      // Limit to max 6 words manually if the LLM hallucinated
      const words = title.split(/\s+/);
      if (words.length > 6) {
        title = words.slice(0, 6).join(" ");
      }

      return title;
    } catch (error: any) {
      console.error(`[LLMService] Error generating chat title with model ${model}:`, error.message || error);
      // Fallback
      let fallback = firstUserMessage.trim();
      if (fallback.length > 60) {
        fallback = fallback.substring(0, 57) + "...";
      }
      return fallback;
    }
  }
}
