import { HfInference } from "@huggingface/inference";

export class LLMService {
  /**
   * Generates an answer using a HuggingFace LLM given a fully constructed prompt.
   * 
   * @param prompt The complete RAG prompt
   * @param model The specific HuggingFace model string (e.g. "Qwen/Qwen3-8B")
   * @returns The generated plain-text answer
   */
  static async generateAnswer(prompt: string, model: string): Promise<string> {
    const apiKey = process.env.HUGGINGFACE_API_KEY;

    if (!apiKey) {
      throw new Error("Missing HUGGINGFACE_API_KEY environment variable.");
    }

    const hf = new HfInference(apiKey);

    try {
      const response = await hf.chatCompletion({
        model: model,
        messages: [{ role: "user", content: prompt }],
        max_tokens: 512,
        temperature: 0.1,
      });

      const generatedContent = response.choices?.[0]?.message?.content;

      if (!generatedContent) {
        throw new Error("No response generated by LLM.");
      }

      return generatedContent.trim();
    } catch (error: any) {
      console.error(`[LLMService] Error generating answer with model ${model}:`, error);
      throw new Error(`LLM Generation Failed: ${error.message}`);
    }
  }
}
